;; Affirmatively Required Basic Features

(require 'init-startup)
(require 'lazy-set-key)
(require 'init-git)
;; Init major mode
(require 'init-c-mode)
(require 'init-web-mode)
;; Init packages configuration
(require 'init-undo-tree)
(require 'init-auto-save)
(require 'init-linum)
(require 'init-autopair)
(require 'init-highlight-parentheses)
(require 'init-rainbow-delimiters)
(require 'init-theme)
(require 'init-ace-jump-mode)
(require 'init-auto-complete)
(require 'init-indent)
(require 'init-auto-indent-mode)
(require 'init-semantic)
(require 'init-hideshow)
(require 'init-ido)
(require 'init-window-number)
(require 'init-yasnippet)
(require 'init-django)
(require 'init-backup)
(require 'init-speedbar)
(require 'init-backup)
;;(require 'init-expand-region)
;;(require 'init-multiple-cursors)
;;(require 'init-popwin)
;;(require 'init-flycheck)
;;(require 'init-jedi)
;;(require 'browse-kill-ring)
;;(require 'init-hl-symbol)
;;(require 'init-backup)
;;(require 'init-ecb)
;;(require 'init-eldoc)

(provide 'init)
