;; Affirmatively Required Basic Features

(require 'init-startup)
(require 'lazy-set-key)
;(require 'basic-toolkit)
(require 'init-mode)

;; Init package and mode
(require 'init-undo-tree)
;;(require 'init-auto-install)
(require 'init-auto-save)
(require 'init-linum)
(require 'init-autopair)
(require 'init-highlight-parentheses)
(require 'init-rainbow-delimiters)
(require 'init-ace-jump-mode)
(require 'init-auto-complete)
(require 'init-indent)
(require 'init-auto-indent-mode)
(require 'init-semantic)
(require 'init-hideshow)
(require 'init-ido)
(require 'init-window-number)
(require 'init-bazaha-c-style)
(require 'init-yasnippet)
(require 'init-backup)
(require 'init-speedbar)
(require 'init-backup)
;;(require 'init-expand-region)
;;(require 'init-multiple-cursors)
;;(require 'init-popwin)
;;(require 'init-flycheck)
;;(require 'init-jedi)
;;(require 'browse-kill-ring)
;;(require 'init-hl-symbol)
;;(require 'init-backup)
;;(require 'init-ecb)
;;(require 'init-eldoc)

(provide 'init)
